# Generated by Django 6.0.2 on 2026-02-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('es_vencido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aval', to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('modalidad', models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual')], max_length=1)),
                ('total_cuotas', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('numero_cuota', models.IntegerField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='prestamos.prestamo')),
            ],
        ),
    ]
