# Generated by Django 6.0.2 on 2026-03-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='curp_aval',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='direccion_aval',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nombre_aval',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='parentesco_aval',
            field=models.CharField(default='', help_text='Ej. Amigo, Familiar, Vecino', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='telefono_aval',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
