# Generated by Django 6.0.2 on 2026-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_activo_prestamo_curp_aval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='garantia_aval',
            field=models.CharField(default='', help_text='Ej. Laptop', max_length=50),
            preserve_default=False,
        ),
    ]
