# Generated by Django 6.0.2 on 2026-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_prestamo_garantia_aval'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='monto_total_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
