# Generated by Django 6.0.2 on 2026-03-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_monto_total_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-03'),
            preserve_default=False,
        ),
    ]
