# Generated by Django 6.0.2 on 2026-03-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamo_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='garantia_aval',
            new_name='garantia_descripcion',
        ),
    ]
