# Generated by Django 6.0.2 on 2026-03-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_rename_garantia_aval_prestamo_garantia_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='total_cuotas',
            new_name='cuotas',
        ),
    ]
