# Generated by Django 6.0.2 on 2026-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_rename_total_cuotas_prestamo_cuotas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='monto_pago',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='abono',
            old_name='numero_cuota',
            new_name='semana_numero',
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
