# Generated by Django 6.0.2 on 2026-03-10 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_rename_monto_pago_abono_monto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_penalizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(default='Recargo diario por mora (1.5%)', max_length=255)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='prestamos.prestamo')),
            ],
        ),
    ]
