# Generated by Django 6.0.2 on 2026-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_penalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalizacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='penalizacion',
            name='motivo_condonacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
