# Generated by Django 6.0.2 on 2026-03-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_penalizacion_activa_penalizacion_motivo_condonacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalizacion',
            name='fecha_condonacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
