# Generated by Django 5.2.8 on 2026-03-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_penalizacion_fecha_condonacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='curp_aval',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(choices=[('I', 'Individual'), ('G', 'Grupal')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.cliente'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('integrantes', models.ManyToManyField(related_name='mis_grupos', to='prestamos.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='prestamos.grupo'),
        ),
    ]
