# Generated by Django 5.2.8 on 2026-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0012_remove_prestamo_curp_aval_prestamo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='curp_aval',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
