# Generated by Django 6.0.2 on 2026-03-15 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_prestamo_curp_aval'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='hora_pago',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
