# Generated by Django 6.0.2 on 2026-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0014_abono_hora_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='folio_pagare',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
