# Generated by Django 6.0.2 on 2026-03-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0015_prestamo_folio_pagare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_actual', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='folio_pagare',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
