# Generated by Django 6.0.2 on 2026-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0016_contadorfolio_alter_prestamo_folio_pagare'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='modalidad',
            field=models.CharField(choices=[('E', 'Efectivo'), ('D', 'Depósito'), ('T', 'Transferencia')], default='E', max_length=1),
        ),
    ]
