# Generated by Django 6.0.2 on 2026-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0017_abono_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='curp_aval_2',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='direccion_aval_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nombre_aval_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='parentesco_aval_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='telefono_aval_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
